### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by inferrinizzard** [eskimoblood/rc-knob#1]
README should be updated with basic documentation, had to figure everything out based on reading source code and the example page.
Something that covers the general use of the Knob component and each of the subcomponent pieces with each of the props and how to use them.

**Comment by TimDaub** [comment]
This site helped me out: https://eskimoblood.github.io/rc-knob/

But I agree that the readme could be more detailed.

**Comment by eskimoblood** [comment]
Feel free to add a pull request for this as I haven't really time to work on this right now.
