### ISSUE TITLE
Knob not moving correctly when parent node positioned absolutely

### ISSUE THREAD

**Issue by Kutalia** [eskimoblood/rc-knob#47]
When a knob is set in a, let's say, movable graph node which is positioned with `absolute` option, and holding down the left mouse button it doesn't move correctly unless mouse is at a default position the knob was first rendered at.
![gif](https://i.ibb.co/HGQd0V8/unknown-2021-08-17-22-22.gif)

**Comment by vallsv** [comment]
Hi.

I did branch the project to fix this issue. One of the fix is this one: https://github.com/vallsv/rc-knob/commit/e28064fbb517f1072210f1643c23731842956cb6 (not sure this commit is the only one related to this issue)

Hope it can help.

**Comment by Kutalia** [comment]
Thank you. It works as expected.

**Comment by squidis** [comment]
Hi, 

I have a similar problem, the Knob doesn't properly detect which part of it was clicked when using the it in a modal with position fixed. I've had a look at the code in the pr and can't see any changes apart from changing the variable name from pageX to clientX. Am I missing something?

**Comment by vallsv** [comment]
This attributes are part of the mouse event. One is absolute to the page the other one is relative to the view.
But as said, i don't remember if there was other patches, cause what i have linked is just a commit. There is maybe other importnt commits to use from this parent commit

**Comment by squidis** [comment]
Thanks so much, this bug has been dogging me for days. I found [this commit](https://github.com/vallsv/rc-knob/commit/47410863ecd53d6c9e259e6a43a69e513421e4ee) and applied it and it works.
